version: '3'

services:

    db:
        image: postgres:13
        env_file:
        - env/django_db.env
        volumes:
        - ./deploy/db_creation.sh:/docker-entrypoint-initdb.d/init.sh

    web:
        build: .
        # command: pipenv run python manage.py runserver 0.0.0.0:8000
        command: pipenv run gunicorn --log-level debug --access-logfile - --workers 3 --bind 0.0.0.0:8000 backend.wsgi:application
        env_file:
        - env/django_db.env
        - env/django_app.env
        volumes:
        - .:/app
        # pipenv run dvc pull
        # ln -s $(pwd)/backend/dataset $(pwd)/dist/static/data
        - ./backend/dataset:/app/backend/dataset
        - ./backend/dataset:/app/dist/static/data
        ports:
        - "8000:8000"
        depends_on:
        - db

    nginx:
        build: ./nginx
        ports:
          - 80:80
        depends_on:
          - web
